"""[users]: add name condition not null; add password

Revision ID: 22c6e30770b8
Revises: 1bf9696808a5
Create Date: 2023-05-24 04:58:33.390774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22c6e30770b8'
down_revision = '1bf9696808a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_name'), ['name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_name'), type_='unique')

    # ### end Alembic commands ###
