"""[notifications]: add table

Revision ID: aed300cf2890
Revises: ba3bbb8c38da
Create Date: 2023-05-31 01:18:55.353140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aed300cf2890'
down_revision = 'ba3bbb8c38da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('notificaion_id', sa.String(), nullable=False),
    sa.Column('notifcation_type', sa.Enum('ACCOUNT_EXPIRED', 'ACCOUNT_EXPIRED_SOON', 'ACCOUNT_LOGINS_LIMIT_EXCEEDED', name='notificationtype', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('notificaion_id', name=op.f('pk_notifications'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    # ### end Alembic commands ###
